tenancy_ocid="<tenancy_ocid>"
compartment_ocid="<compartment_ocid>"
user_ocid="<user_ocid>"
fingerprint="<user fingerprint>"
private_key_path="<PEM based private key>"
region="<us-phoenix-1 or us-ashburn-1 or any other region available>"
